apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: passos-magicos-pushgateway
  namespace: mle-system
  labels:
    release: kps-r8pi
    app: passos-magicos
spec:
  namespaceSelector:
    matchNames:
      - passos-magicos
  selector:
    matchLabels:
      app: passos-magicos
      component: pushgateway
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
